run:
  timeout: 3m
  allow-parallel-runners: true
  skip-dirs:
    # used for testing/experiments
    - "cmd/oncecmd"
    # testing
    - "internal/ddb"

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib

      - go-ethereum.Subscription
      - mapstructure.DecodeHookFunc
      - rueidis.Client
      - w3types.Caller

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - goerr113
    - golint
    - gomnd
    - interfacer
    - lll
    - maintidx
    - maligned
    - nestif
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
