run:
    timeout: 3m
    allow-parallel-runners: true
    concurrency: 4
    tests: false
    skip-dirs:
        # used for testing/experiments
        - "cmd/oncecmd"
        # testing
        - degendata/
        - "internal/ddb"
        - "ignored"

linters-settings:
    ireturn:
        allow:
            - anon
            - error
            - empty
            - stdlib

            - go-ethereum.Subscription
            - mapstructure.DecodeHookFunc
            - rueidis.Client
            - w3types.Caller

linters:
    enable-all: true
    # fast: true
    disable:
        - cyclop
        - depguard
        - exhaustive
        - exhaustivestruct
        - exhaustruct
        - forbidigo
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - gocyclo
        - godox
        - goerr113
        - golint
        - gomnd
        - interfacer
        - ireturn
        - lll
        - maintidx
        - maligned
        - nestif
        - tagliatelle
        - varnamelen
        - wrapcheck
        - wsl
