
name: gloomberg build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write
  packages: write
  # issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
        check-latest: true
        # cache: true

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
