name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    permissions: { contents: write, packages: write }

    env:
      REGISTRY: ghcr.io
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: { fetch-depth: 0 }

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with: { cache: true, check-latest: true, go-version-file: "go.mod" }

      - name: Run GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --clean --snapshot
        env:
          REGISTRY: ${{ env.REGISTRY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (release)
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          REGISTRY: ${{ env.REGISTRY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
