name: golangci-lint

#  push:  # { branches: [master, main], tags: [v*] }
on: [push, pull_request, workflow_dispatch]

# Optional: allow read access to pull request. Use with `only-new-issues` option.
permissions: { contents: read } # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with: { cache: false, check-latest: true, go-version-file: "go.mod" }

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: { version: latest }
