name: golangci-lint

on:
    push: { branches: [master, main, dev/*], tags: [v*] }
    pull_request:
    workflow_dispatch:

# Optional: allow read access to pull request. Use with `only-new-issues` option.
permissions: { contents: read } # pull-requests: read

jobs:
    golangci:
        name: lint
        runs-on: ubuntu-latest

        # cancel already in-progress jobs or runs for the current workflow
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with: { cache: false, check-latest: true, go-version-file: "go.mod" }

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with: { version: latest }
